dist: trusty
sudo: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

git:
  submodules:
    false

addons:
  apt:
    sources:
    - sourceline: 'ppa:ethereum/ethereum'
    packages:
    - ethereum

before_install:
  - git submodule update --init --recursive
  - ./scripts/frg-ethereum-runners/ci-dep-install.sh

script:
  - npm run lint
  - ./scripts/test.sh

notifications:
  email:
    - eng@fragments.org
  slack: fragmentsorg:2bN0L0FCZZ0illBRyPucRZkV
