dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/zos
    - $(npm config get prefix)/bin/ganache-cli
before_install:
  - npm install -g npx
script:
  - npx setup-local-chains
  - npm run lint
  - ./scripts/test.sh
notifications:
  email:
    - eng@fragments.org
  slack: fragmentsorg:2bN0L0FCZZ0illBRyPucRZkV
